# Generated by Django 4.0.4 on 2022-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaribImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caribName', models.CharField(max_length=10)),
                ('caribFile', models.CharField(max_length=256)),
                ('caribJson', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locx', models.SmallIntegerField()),
                ('locy', models.SmallIntegerField()),
                ('angle', models.FloatField()),
                ('scale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('fsize', models.IntegerField()),
                ('fdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.IntegerField()),
            ],
        ),
    ]
