# Generated by Django 4.0.4 on 2022-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaribImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=256)),
                ('time', models.FloatField(default=0)),
                ('json', models.JSONField(default=dict)),
                ('cfile', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FileDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirName', models.CharField(max_length=255)),
                ('fileList', models.JSONField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locx', models.SmallIntegerField()),
                ('locy', models.SmallIntegerField()),
                ('angle', models.FloatField()),
                ('scale', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('fsize', models.IntegerField()),
                ('fhuman', models.CharField(default='0', max_length=20)),
                ('fdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.IntegerField()),
            ],
        ),
    ]
