# Generated by Django 4.0.4 on 2022-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirName', models.CharField(max_length=255)),
                ('fileList', models.JSONField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
